import 'package:flutter/material.dart';
import '../theme.dart';

class TermsConditionsScreen extends StatelessWidget {
  const TermsConditionsScreen({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: AppTheme.charcoal,
      appBar: AppBar(
        backgroundColor: Colors.transparent,
        elevation: 0,
        leading: IconButton(
          icon: const Icon(Icons.close, color: Colors.white),
          onPressed: () => Navigator.pop(context),
        ),
        title: const Text(
          'TERMS & CONDITIONS',
          style: TextStyle(
            fontSize: 12,
            fontWeight: FontWeight.bold,
            letterSpacing: 2,
            color: Colors.white60,
          ),
        ),
        centerTitle: true,
      ),
      body: SingleChildScrollView(
        padding: const EdgeInsets.all(24.0),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            const Text(
              'Agreement to Terms',
              style: TextStyle(
                fontSize: 24,
                fontWeight: FontWeight.bold,
                color: AppTheme.sunsetOrange,
              ),
            ),
            const SizedBox(height: 16),
            const Text(
              'By accessing or using FitRoute, you agree to be bound by these Terms and Conditions. If you do not agree with any part of these terms, you may not access the service.',
              style: TextStyle(color: Colors.white70, height: 1.6),
            ),
            const SizedBox(height: 32),
            _Section(
              title: '1. Personal Information',
              content: 'We collect metrics such as weight, age, and fitness goals to provide personalized meal and workout plans. This data is processed locally and stored securely.',
            ),
            _Section(
              title: '2. Health Disclaimer',
              content: 'The plans provided are generated by simulation/AI logic. Always consult with a healthcare professional before starting any new diet or exercise program.',
            ),
            _Section(
              title: '3. Subscription & Billing',
              content: 'Certain features may require a paid subscription. All payments are processed through secure third-party providers.',
            ),
            _Section(
              title: '4. User Conduct',
              content: 'Users are responsible for maintaining the confidentiality of their account and password and for restricting access to their device.',
            ),
            const SizedBox(height: 48),
            Center(
              child: Text(
                'Last Updated: March 2026',
                style: TextStyle(
                  fontSize: 12,
                  color: Colors.white.withOpacity(0.3),
                  fontStyle: FontStyle.italic,
                ),
              ),
            ),
            const SizedBox(height: 32),
          ],
        ),
      ),
    );
  }
}

class _Section extends StatelessWidget {
  final String title;
  final String content;

  const _Section({required this.title, required this.content});

  @override
  Widget build(BuildContext context) {
    return Padding(
      padding: const EdgeInsets.only(bottom: 24.0),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Text(
            title,
            style: const TextStyle(
              fontSize: 18,
              fontWeight: FontWeight.bold,
              color: Colors.white,
            ),
          ),
          const SizedBox(height: 8),
          Text(
            content,
            style: const TextStyle(color: Colors.white60, height: 1.6),
          ),
        ],
      ),
    );
  }
}
